# Generated by Django 4.0 on 2023-11-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

   


