# Generated by Django 4.0 on 2023-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_auto_20231111_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
