# Generated by Django 4.0 on 2023-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_broadcastnotification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='message',
            field=models.TextField(unique=True),
        ),
    ]
