# Generated by Django 4.0 on 2023-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_alter_broadcastnotification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='message',
            field=models.TextField(),
        ),
    ]
