# Generated by Django 4.0 on 2023-11-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0006_broadcastnotification_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='is_read',
        ),
    ]
