# Generated by Django 4.0 on 2023-11-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0007_remove_broadcastnotification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
