# Generated by Django 4.2.7 on 2023-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_userpreference_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10),
        ),
    ]
